[phases.setup]
aptPkgs = []

[phases.install]
cmd = "cd shipfile-s3-sharing-main/backend && npm install"

[phases.build]
cmd = "echo 'No build step required'"

[start]
cmd = "cd shipfile-s3-sharing-main/backend && npm start"