[variables]
WORKDIR = "/app/backend"

[phases.setup]
aptPkgs = []

[phases.install]
cmd = "cd backend && npm ci"

[phases.build]
cmd = "echo 'No build step required'"

[start]
cmd = "cd backend && npm start"